name: Generate Snake Animation

on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *" 
  
  # Permite rodar manualmente na aba Actions para testar
  workflow_dispatch:
  
  # Roda sempre que houver push na main (opcional)
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 1. Baixa o repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Gera a Animação da Cobra
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jefe-dev-rs
          # Gera dois arquivos: um normal e um para dark mode
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Envia os arquivos para a branch 'output'
      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
